### ISSUE TITLE
Can't get data into new details array

### ISSUE THREAD

**Issue by tedkulp** [opsgenie/logstash-output-opsgenie#2]
Hello,

I'm trying to get data into the details variable, and it doesn't seem to be possible using logstash plugins directly. The mutate plugin doesn't seem to have the ability to add to an array. There seemed to be some hints to using numeral notation (`add_field => [ "details[0]", "severity:%{severity}"]`), but it just gives me badly formed json:

```
"details": {
  "0": "severity:ERROR"
},
```

I then tried doing this directly with the ruby plugin:

```
ruby {
  code => "
    event['details'] = ['test:test', 'test2:test2']
  "
}
```

But that just makes a hard error:

```
"error"=>"MapperParsingException[object mapping [details] trying to serialize a value with no field associated with it, current value [test:test]]"}}
```

I've been reading docs and examples for hours, but I keep striking out. Logstash's config files seem to be optimized for using hashes. How did you end up using this when it was switched? Because I'm at a loss.

Thanks!

**Comment by tubaozturk** [comment]
Hi Ted, 

A working configuration example can find from our [support document](https://www.opsgenie.com/docs/integrations/logstash-integration) Configuration with the format below works as expected. 

``` mutate{
    add_field => {
            "opsgenieAction" => "create"
            "alias" => "%{host}"
            "actions" => ["ping"]
            "entity" => "sample_entity"
            "details" => [
                "prop1:%{host}",
                "prop2:value2"
            ]
    }
}
```

Please give this format a shot. Meanwhile, we'll take another look to get details field in a better way.

Thanks!

**Comment by tubaozturk** [comment]
Hi Ted,

A new version of the plugin is now available in [rubygems.org](https://rubygems.org/gems/logstash-output-opsgenie/versions/2.0.4). Now you can add details like the following:

```
filter{
    mutate{
        add_field => {
            opsgenieAction => "create"
            "[details][prop1]"=> "val1"
            "[details][prop2]" => "val2"
            "[details][prop3]" => "val3"
        }
    }   
}
```

Thanks!

**Comment by tedkulp** [comment]
Tuba,

Thank you so much for your quick fix. The update definitely helped. I had also tried the original way you described and that wasn't working either for some reason. But the new version worked perfectly and is also a little easier to work with using logstash's weird plugins.

Thanks!
