### ISSUE TITLE
healthcheck/heartbeat support

### ISSUE THREAD

**Issue by danielmotaleite** [opsgenie/logstash-output-opsgenie#3]
In logstash we can generate a healthcheck via 
```
  heartbeat {
    interval => 60
    type => "heartbeat"
  }
```
But then on the opgenie output we can only create alerts, from what i check, there is no support for healthcheck:

```
# The value of this field holds the name of the action will be executed in OpsGenie.
# This field must be in Event object. Should be one of "create", "close", "acknowledge" or "note". Other values will be discarded.
```

So please expand this to support healtcheck or update documentation with one example if already possible.

**Comment by halitokumus** [comment]
Thanks, we'll look into it.

**Comment by ufukoz** [comment]
Thanks for contacting us.

We've created an issue for your request. We'll look into it as soon as possible. In the meantime maybe you'd like to check our Heartbeat API and Heartbeat integration. They may be what you need.

Here is the link: https://www.opsgenie.com/docs/rest-api/heartbeat-api-v2

Please feel free to contact us with any other issue.

**Comment by danielmotaleite** [comment]
For someone looking for heartbeat support for logstash, i'm using this:

```
if "heartbeat" in [tags] {
    exec {
      command => " curl -XPOST https://api.opsgenie.com/v1/json/heartbeat/send -d '{ \"apiKey\": \"your_api_key\", \"name\" : \"logstash\" }' & "
    }
}
```

where the name: logstash is the heartbeat name in opsgenie.
you can then create a alert in the opsgenie integratin config using that heartbeat data
