### ISSUE TITLE
Logstash plugin manager was renamed

### ISSUE THREAD

**Issue by gabipetrovay** [opsgenie/logstash-output-opsgenie#6]
As of Logstash 5.4, the plugin manager [was renamed](https://www.elastic.co/guide/en/logstash/current/breaking-changes.html#_plugin_manager_renamed) to `bin/logstash-plugin`.

Maybe you should rename also in the master branch in the documentation and make a note on this as well for people using Logstash version pre-`5.4`.

So instead of:

```bash
bin/plugin install logstash-output-opsgenie
```

it should be:

```bash
bin/logstash-plugin install logstash-output-opsgenie
```

**Comment by bcelenk** [comment]
Thanks for notifying @gabipetrovay 
We've updated the relevant parts since it might be a bit confusing for newcomers.
