### ISSUE TITLE
logstash-output-opsgenie installation not working in Logstash 5.4.2

### ISSUE THREAD

**Issue by gabipetrovay** [opsgenie/logstash-output-opsgenie#7]
Installation not working in Logstash v`5.4.2`. Was this tested?

See [this SO question](https://stackoverflow.com/questions/44882792/installing-and-configuring-opsgenie-logstash-plugin-in-logstash-5-4) for details.

**Comment by halitokumus** [comment]
Hi gabi, I accepted your merge request and published the new gem. Thanks for the contribution. If it's working fine for you now, I'd like to close the issue. Can you check it out?

**Comment by gabipetrovay** [comment]
I will check it tomorrow and then we can close it. Since I did not write the tests for it, it is worth doing a smoke test.

**Comment by halitokumus** [comment]
Hi gabi, is it OK if I close this?
